### ISSUE TITLE
日時フォーマットの固定化

### ISSUE THREAD

**Issue by ShieruCHR** [Ithi075/My-Diary.md#1]
Commit e241c04f149cb12535b324a8de2b06c5f48ccd10 にて、9/4と9/5分の日記が書かれていますが、
9/3の日時フォーマットが `yyyy年mm月dd日(E)`なのに対し、9/4と9/5の日記は`mm月dd日(E)`形式で記述されています。

どちらかに統一したほうが良いのではないでしょうか？

**Comment by ShieruCHR** [comment]
Fixed in 4e3db37a145f31ae3ca61dfa642171d42272cac8

**Comment by Ithi075** [comment]
仰る通りですね
ありがとうございます
